version: 2.1

jobs:
  build:
    docker:
        - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: deploy-cloudFormation
          environment:
            AWS_CLI_STR_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_CLI_STR_PROFILE_NAME: $AWS_SECRET_ACCESS_KEY
          command: |
            aws cloudformation deploy --template-file .circleci/files/vpc.yml \
            --tags project=proyecto-eks --region us-east-1 --stack-name deploy-vpc \
            --parameter-overrides VpcBlock=192.168.0.0/16 \
            Subnet01Block=192.168.64.0/18 Subnet02Block=192.168.128.0/18 \
            Subnet03Block=192.168.192.0/18

      - run:
          name: obtain-information
          command: |
            listSubnets=$(aws ec2 describe-subnets --filters "Name=tag:aws:cloudformation:stack-name,Values=deploy-vpc" \
            --query "Subnets[*].SubnetId" --region us-east-1 --out json)

            securityGroup=$(aws ec2 describe-security-groups --region us-east-1 \
            --filters "Name=tag:aws:cloudformation:stack-name,Values=deploy-vpc" \
            --query "SecurityGroups[0].GroupId")

      - run:
          name: deploy-AWSCli
          command: |
            aws eks --region us-east-1 create-cluster --name eks --role-arn arn:aws:iam::403107932867:role/CreateEKS \
            --resources-vpc-config subnetIds="$listSubnets",securityGroupIds=$securityGroup

  
workflows:
  default:
    jobs:
      - build:
        filters:
          branches:
            only: [deploy-infraestructure]


