version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1
  kubernetes: circleci/kubernetes@1.0.0 

jobs:      
  create_infraestructure:
    docker:
        - image: cimg/base:2021.04
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - run:
          name: Install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin     
      - run:
          name: Create kubernetes cluster
          environment:
            AWS_CLI_STR_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_CLI_STR_PROFILE_NAME: $AWS_SECRET_ACCESS_KEY
          command: |
            clusterName="capstone-${CIRCLE_WORKFLOW_ID:0:7}"
            eksctl create cluster --name=Eks --region=us-east-1 --zones=us-east-1a,us-east-1b
            curl https://kvdb.io/AnCL2AcTbjnej3iwokxmCv/clusterName -d Eks

  deploy_build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u ${userdocker} -p ${passworddocker}
            docker tag app "${userdocker}/app:${CIRCLE_SHA1}"
            docker push "${userdocker}/app:${CIRCLE_SHA1}"

  install_deployment:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: Install awscli
          
          command: |
            curl --silent "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
            -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
      - run:
          name: Install and configure kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s \
            https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && sudo install \
            -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && kubectl version --client
      - deploy:
          name: Deploy release
          environment:
            AWS_CLI_STR_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_CLI_STR_PROFILE_NAME: $AWS_SECRET_ACCESS_KEY
          command: |
            aws eks update-kubeconfig --region us-east-1 --name eks_2
            kubectl apply -f app-deployment.yml

workflows:
  default:
    jobs:
      - create_infraestructure:
          filters:
            branches:
              only: [deployment]
      - deploy_build
      - install_deployment:
          requires: [deploy_build]




